services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m ubb
    envVars:
      - key: BOT_TOKEN
        value: 7834214536:AAHhfo8u0AvBQLDfcnfMXJIVUApStNbGzX8
